name: Linting Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linting:
    name: Lint Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy requests

    - name: Run Black formatting check
      run: black --check --diff .

    # - name: Run isort import sorting
    #   run: isort --check --diff .

    # - name: Run flake8 linting
    #   run: flake8 .

    # # Optional: Run mypy type checking
    # - name: Run mypy type checking
    #   run: mypy --config-file mypy.ini .
